### ISSUE TITLE
verify() unit test with 2 threshold and 3 keys

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Antelope-SSI-Toolkit#14]
https://github.com/Tonomy-Foundation/EOS-network-foundation-grant-framework/blob/ssi-toolkit/applications/ssi-toolkit-verifiable-credentials.md#milestone-2-verifiable-credential-verify

Definition of done

- [ ] Function exists to verify that a verifiable credential was signed using an Antelope account
- [ ] unit test that validates that signature is correct for an account permission with 2 threshold and 3 keys

**Comment by Rebal67** [comment]
to review this please clone all these repos and install, build them in the following order:
https://github.com/Tonomy-Foundation/did-resolver/pull/2 
https://github.com/Tonomy-Foundation/did-jwt/pull/4
https://github.com/Tonomy-Foundation/did-jwt-vc/pull/2
https://github.com/Tonomy-Foundation/antelope-did-resolver/pull/3
https://github.com/Tonomy-Foundation/antelope-did/pull/2
https://github.com/Tonomy-Foundation/Antelope-SSI-Toolkit/pull/28

then run the tests in Antelope SSI repo
