### ISSUE TITLE
Publish to npmjs.com

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Antelope-SSI-Toolkit#9]
https://github.com/Tonomy-Foundation/EOS-network-foundation-grant-framework/blob/ssi-toolkit/applications/ssi-toolkit-verifiable-credentials.md#milestone-2-verifiable-credential-verify

Definition of done

Do this for all of the repositories we have changed:

- [ ] As an appropriate version number is set
- [ ] antelope-ssi-toolkit is published in a compact format on npmjs.com with at least 2 collaborator administrators
- [ ] npmjs.com Page shows instructions for how to install and use the library
- [ ] update packages to use the published package as dependency, instead of the file reference

**Comment by Rebal67** [comment]
https://www.npmjs.com/search?q=%40tonomy
once jack accepts the organization invite packages will have 2 collaborators
